namespace: evertrust
name: horizon
version: 0.1.1
readme: README.md
authors:
- Adrien Ducourthial <adu@evertrust.fr>

description: ''
license_file: ''

tags: [evertrust, horizon]
repository: https://github.com/EverTrust/horizon-ansible
homepage: https://github.com/EverTrust/horizon-ansible
issues: https://github.com/EverTrust/horizon-ansible/issues

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml