namespace: evertrust
name: horizon
version: 1.4.2
readme: README.md
authors:
- EverTrust R&D (@Evertrust)

description: 'EverTrust Horizon collection for Ansible.'
license_file: 'LICENSE.md'

tags: [evertrust, horizon]
repository: https://github.com/EverTrust/horizon-ansible
homepage: https://github.com/EverTrust/horizon-ansible
documentation: https://evertrust.github.io/horizon-ansible
issues: https://github.com/EverTrust/horizon-ansible/issues

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .idea
  - venv
  - docs/html