---
- hosts: webserver
  become: yes
  tasks:
  - name: get certificate
    shell: "cat /etc/nginx/ssl-files/{{domain}}.crt"
    register: data

  - name: Stop Nginx Services
    service:
      name: nginx
      state: stopped

  - name: Uninstall Nginx
    become: yes
    apt:
      name: nginx
      state: absent

  - name: Clean
    command: rm -r -f /etc/nginx /var/log/nginx
    become: true

  - name: horizon_revoke
    evertrust.horizon.horizon_revoke:
      endpoint: "https://horizon-demo.evertrust.fr" 
      x_api_id: "{{api_id}}"
      x_api_key: "{{api_key}}"
      certificate_pem: "{{ data['stdout'] }}"
