- hosts: webserver
  become: yes
  tasks:
  - name: Retrieving current certificate
    shell: "cat /etc/nginx/ssl/{{ domain }}.crt"
    register: current_certificate

  - name: Looking up for current certificate in Horizon
    set_fact:
      current_lookup_result: >-
        {{ query('evertrust.horizon.horizon_lookup', certificate_pem=current_certificate['stdout'], x_api_id=api_id, x_api_key=api_key, endpoint=horizon_endpoint) }}

  - name: Calculating certificate renewal date
    set_fact:
      should_renew: "{{(a|int / 1000) - (c|int *86400) < b|int}}"
    vars:
      a: "{{ current_lookup_result['notAfter'] }}"
      b: "{{ ansible_date_time.epoch }}"
      c: "{{ renewal_period }}"

  - name: Renewing certificate if within its renewal period
    evertrust.horizon.horizon_enroll:
      endpoint: "{{ horizon_endpoint }}"
      key_type: "{{ current_lookup_result['keyType'] }}"
      x_api_id: "{{ api_id }}"
      x_api_key: "{{ api_key }}"
      profile: "{{ current_lookup_result['profile'] }}"
      subject: 
        dn: "{{ current_lookup_result['dn'] }}"
      sans: "{{ current_lookup_result['subjectAlternateNames'] }}"
      labels: "{{ current_lookup_result['labels'] }}"
    register: enrolled_certificate
    when: should_renew|bool == true

  - name: Uploading the renewed certificate
    copy:
      content: "{{ enrolled_certificate['certificate']['certificate'] }}"
      dest: "/etc/nginx/ssl/{{ domain }}.crt"
    when: should_renew|bool == true
  
  - name: Uploading the renewed certificate private key
    copy:
      content: "{{ enrolled_certificate['key'] }}"
      dest: "/etc/nginx/ssl/{{ domain }}.key"
    when: should_renew|bool == true

  - name: Redeploying the {{ domain }} index page
    template:
      src: ../templates/index.html.j2
      dest: "/var/www/{{ domain }}/index.html"
      owner: "www-data"
      group: "www-data"
      mode: '0644'
    when: should_renew|bool == true

  - name: Restarting nginx
    service:
      name: nginx
      state: restarted
    when: should_renew|bool == true

  - name: Revoking the previous certificate
    evertrust.horizon.horizon_revoke:
      endpoint: "{{ horizon_endpoint }}" 
      x_api_id: "{{ api_id }}"
      x_api_key: "{{ api_key }}"
      certificate_pem: "{{ current_certificate['stdout'] }}"
    when: should_renew|bool == true