- hosts: webserver
  become: yes
  tasks:
  - name: Updating APT cache
    apt: update_cache=yes   
  
  - name: Installing nginx
    apt: 
      name: nginx 
      state: latest
  
  - name: Get webra enroll template
    evertrust.horizon.horizon_template:
      endpoint: "{{ horizon_endpoint }}"
      x_api_id: "{{ api_id }}"
      x_api_key: "{{ api_key }}"
      profile: "{{ profile }}"
      workflow: "enroll"
    register: template

  - name: Generate an OpenSSL private RSA key with size-2048 bits
    openssl_privatekey:
      path: /tmp/ansible_key
      type: "{{ template.capabilities.defaultKeyType | split('-') | first | upper }}"
      size: "{{ template.capabilities.defaultKeyType | split('-') | last }}"
      return_content: true
    register: privatekey

  - name: Generate an OpenSSL certificate signing request file bases on input key values
    openssl_csr:
      path: /tmp/ansible_csr
      privatekey_path: "{{ privatekey.filename }}"
    register: csr

  - name: Enrolling a certificate on Horizon for domain {{ domain }}
    evertrust.horizon.horizon_enroll:
      endpoint: "{{ horizon_endpoint }}"
      mode: "decentralized"
      key_type: "{{ key_type }}"
      x_api_id: "{{ api_id }}"
      x_api_key: "{{ api_key }}"
      profile: "{{ profile }}"
      subject:
        cn.1: "{{ domain }}"
        ou.1: "Web Server"
      sans:
        dnsname: 
          - "{{ domain }}"
          - "www.{{ domain }}"
      labels:
        business_unit: "{{ business_unit }}"
        ansible_host: "{{ ansible_host }}"
      contact_email: "{{ contact_email }}"  
      csr:
        src: "{{csr.filename}}"
    register: enrolled_certificate

  - name: Creating the SSL directory
    file:
      path: /etc/nginx/ssl
      state: directory
      mode: '0775'
      owner: "www-data"
      group: "www-data"

  - name: Uploading the {{ domain }} certificate
    copy:
      content: "{{ enrolled_certificate['certificate']['certificate'] }}"
      dest: "/etc/nginx/ssl/{{ domain }}.crt"
      mode: '0660'
      owner: "www-data"
      group: "www-data"
    
  - name: Uploading the {{ domain }} private key
    copy:
      content: "{{ privatekey.privatekey }}"
      dest: "/etc/nginx/ssl/{{ domain }}.key"
      mode: '0660'
      owner: "www-data"
      group: "www-data"
    
  - name: Creating the {{ domain }} webroot directory
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'
      owner: "www-data"
      group: "www-data"

  - name: Deploying the {{ domain }} index page
    template:
      src: ../templates/index.html.j2
      dest: "/var/www/{{ domain }}/index.html"
      owner: "www-data"
      group: "www-data"
      mode: '0644'

  - name: Removing the default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Uploading the {{ domain }} site config
    template:
      src: ../templates/nginx.conf.j2
      dest: "/etc/nginx/sites-available/{{ domain }}"
      owner: "www-data"
      group: "www-data"
      mode: '0644'

  - name: Ensuring that {{ domain }} site exists
    stat: 
      path: "/etc/nginx/sites-enabled/{{domain}}"
    register: stat_result

  - name: Enabling the {{ domain }} site
    command: "ln -s /etc/nginx/sites-available/{{ domain }} /etc/nginx/sites-enabled"
    when: not stat_result.stat.exists

  - name: Restarting nginx
    service:
      name: nginx
      state: restarted
