- hosts: webserver
  become: yes
  tasks:
  - name: Retrieving current certificate for domain {{ domain }}
    shell: "cat /etc/tomcat9/ssl/{{ domain }}.crt"
    register: current_certificate

  - name: Stopping tomcat
    become: yes
    service:
      name: tomcat9
      state: stopped

  - name: Uninstalling tomcat
    apt: 
      name: tomcat9
      state: absent
      purge: yes

  - name: Revoking the current certificate
    evertrust.horizon.horizon_revoke:
      endpoint: "{{ horizon_endpoint }}"
      x_api_id: "{{ api_id }}"
      x_api_key: "{{ api_key }}"
      certificate_pem: "{{ current_certificate['stdout'] }}"