---
- hosts: webserver
  become: yes
  vars:
    path: "/etc/tomcat9/ssl-files/{{domain}}.crt"
    content: "{{ lookup('file', path) }}"
  tasks:
  - name: get certificate
    ansible.builtin.fetch:
      src: /etc/tomcat9/ssl-files/{{domain}}.crt
      dest: /tmp/

  - name: Stop tomcat
    become: yes
    service: 
      name: tomcat9
      state: stopped

  - name: uninstall tomcat
    apt: 
      name: tomcat9
      state: absent
      purge: yes

  - name: Clean
    command: rm -r -f /etc/tomcat9 /var/log/tomcat9
    become: true
  
  - name: horizon_revoke
    evertrust.horizon.horizon_revoke:
      endpoint: "https://horizon-demo.evertrust.fr" 
      x_api_id: "{{api_id}}"
      x_api_key: "{{api_key}}"
      certificate_pem: 
        src: "/tmp/ubuntu/etc/tomcat9/ssl-files/{{ domain }}.crt"