---
- hosts: webserver
  become: yes
  
  tasks:
  - name: get certificate
    shell: "cat /etc/apache2/ssl-files/{{domain}}.crt"
    register: data
      
  - name: Stop Apache Services
    become: yes
    service:
      name: apache2
      state: stopped

  - name: Uninstall Apache
    apt:
      name: apache2
      state: absent
      purge: yes

  - name: Clean
    command: rm -r -f /etc/apache2 /var/log/apache2
    become: true
  
  - name: horizon_revoke
    evertrust.horizon.horizon_revoke:
      endpoint: "https://horizon-demo.evertrust.fr" 
      x_api_id: "{{api_id}}"
      x_api_key: "{{api_key}}"
      certificate_pem: "{{ data['stdout'] }}"

  