= evertrust.horizon.feed
Doc Writer Adrien Ducourthial <adu@evertrust.fr>
v2.0, {docdate}
:version: 2.0
:imagesdir: ./images
:title-page:
:numbered:
:toc:

== Synopsis
Feed a certificate to Horizon

== Requirements

== Parameters
=== Authentication Parameters

To authenticate on Horizon, you have to chose between log in with a certificate or with your login password. +
If you inform all the parameters, you will be log in priority by your certificate authent.

|===
| Parameter | Choices/Defaults | Configuration

| *client_cert* +
_path_
|
a| * The location of a client side certificate.
* authent value

| *client_key* +
_path_
|
a| * The location of a client side certificate's key.
* authent value

| *x_api_id* +
_string_
| 
a| * Horizon authentication id.
* authent value

| *x_api_key* +
_string_
|
a| * Horizon authentication key.
* authent value

| *ca_bundle* +
_path_
|
a| * The location of a CA Bundle to use when validating SSL certificates.
* optionnal
|===

=== Plugin Parameters

|===
| Parameter | Choices/Defaults | Configuration

| *endpoint* +
_string_
|
| Url of the API.

| *campaign* +
_string_
|
| 

| *ip* +
_adress_
|
| IP adress.

| *certificate* +
_string_
|
| A certificate pem, or the path to the certificate pem file.

| *hostnames*
|
| 

| *operating_systems*
|
|

| *paths* 
|
|

| *usages*
|
|

|===

== Examples
``` yaml
---
- name: test discovery
  evertrust.horizon.feed:

    x_api_id: "myId"
    x_api_key: "myKey"

    endpoint: "https://url-of-the-api"

    campaign: campaign1
    ip: localhost
    certificate: <certificate_in_pem>

- name: test discovery
  evertrust.horizon.feed:

    x_api_id: "myId"
    x_api_key: "myKey"

    endpoint: "https://url-of-the-api"

    campaign: campaign1
    ip: localhost
    certificate: 
      src: pem/file/path
```

== Status
=== Authors
- Evertrust R&D