= evertrust.horizon.horizon_recover

== Synopsis
Recover a certificate on Horizon

== Requirements

== Parameters
|===
| Parameter | Choices/Defaults | Configuration

| *x_api_id* +
_string_
| 
a| * Horizon authentication id.
* authent value

| *x_api_key* +
_string_
|
a| * Horizon authentication key.
* authent value

| *ca_bundle* +
_path_
|
a| * The location of a CA Bundle to use when validating SSL certificates.
* authent value

| *client_cert* +
_path_
|
a| * The location of a client side certificate.
* authent value

| *client_key* +
_path_
|
a| * The location of a client side certificate's key.
* authent value

| *endpoint* +
_string_
| 
| Url of the API.

| *profile* +
_string_
| 
| Horizon profile to recover certificate.

| *password* +
_string_
|
| Horizon password to recover certificate.

| *certificate_pem* +
_string_
|
| A pem file.

|===

== Examples
``` yaml
--- 
- name: Simple Recover
  evertrust.horizon.horizon_recover:

    endpoint: "https://url-of-the-api"
        
    x_api_id: "myId"
    x_api_key: "myKey"

    certificate_pem: <a_webra_pem_file>

    profile: "profile"
    password: "pAssw0rd"
```

== Status
=== Authors
- Adrien Ducourthial