= Evertrust.horizon.horizon_lookup
Doc Writer Adrien Ducourthial <adu@evertrust.fr>
v2.0, {docdate}
:version: 2.0
:imagesdir: ./images
:title-page:
:numbered:
:toc:

== Synopsis
- Describes attributes of your horizon certificate.
- You can specify one of the listed attribute choices or omit it to see all attributes.

== Requirements

== Parameters
=== Authent Parameters

To be authent on Horizon, you have to chose between log in with a certificate or with your login password. +
If you inform all the parameters, you will be log in priority by your certificate authent.

|===
| Parameter | Choices/Defaults | Configuration

| *client_cert* +
_path_
|
a| * The location of a client side certificate.
* authent value

| *client_key* +
_path_
|
a| * The location of a client side certificate's key.
* authent value

| *x_api_id* +
_string_
| 
a| * Horizon authentication id.
* authent value

| *x_api_key* +
_string_
|
a| * Horizon authentication key.
* authent value

| *ca_bundle* +
_path_
|
a| * The location of a CA Bundle to use when validating SSL certificates.
* optionnal
|===

=== Lookup Parameters

|===
| Parameter | Choices/Defaults | Configuration | Comments

| *endpoint* +
  _string_
|
|
| Url of the API.

| *pem* +
  _string_
| 
| 
| A certificate pem.

| *attributes* +
  _string_ or _dict_
a| * _id
* labels
* module
* profile
* serial
| 
| Attributes from the certificat. 
Return value.

|===

== Examples

``` yaml
vars:
  my_pem: <a_webra_pem_file>
  path_to_pem: 
    src: /path/of/a/webra/pem/file
  x_api_id: "myId"
  x_api_key: "myKey"
  my_endpoint: "https://url-of-the-api"

  with_one: "{{ lookup('evertrust.horizon.horizon_lookup', x_api_id=x_api_id, x_api_key=x_api_key, pem=my_pem, attributes='module', endpoint=my_endpoint) }}"
  # only demanded (str)

  with_list: "{{ lookup('evertrust.horizon.horizon_lookup', x_api_id=x_api_id, x_api_key=x_api_key, pem=my_pem, attributes=['module', '_id'], endpoint=my_endpoint) }}"
  # only those in list (dict)

  without: "{{ lookup('evertrust.horizon.horizon_lookup', x_api_id=x_api_id, x_api_key=x_api_key, pem=path_to_pem, endpoint=my_endpoint) }}"
  # all (dict)
```

== Status
=== Authors
- Adrien Ducourthial
