= evertrust.horizon.recover
Doc Writer Adrien Ducourthial <adu@evertrust.fr>
v2.0, {docdate}
:version: 2.0
:imagesdir: ./images
:title-page:
:numbered:
:toc:

== Synopsis
Recover a certificate on Horizon

== Requirements

== Parameters
=== Authentication Parameters

To authenticate on Horizon, you have to chose between log in with a certificate or with your login password. +
If you inform all the parameters, you will be log in priority by your certificate authent.

|===
| Parameter | Choices/Defaults | Configuration

| *client_cert* +
_path_
|
a| * The location of a client side certificate.
* authent value

| *client_key* +
_path_
|
a| * The location of a client side certificate's key.
* authent value

| *x_api_id* +
_string_
| 
a| * Horizon authentication id.
* authent value

| *x_api_key* +
_string_
|
a| * Horizon authentication key.
* authent value

| *ca_bundle* +
_path_
|
a| * The location of a CA Bundle to use when validating SSL certificates.
* optionnal
|===

=== Plugin Parameters

|===
| Parameter | Choices/Defaults | Configuration

| *endpoint* +
_string_
| 
| Url of the API.

| *password* +
_string_
|
| Horizon password to recover certificate.

| *certificate_pem* +
_string_
|
| A certificate pem, or the path to the certificate pem file.

|===

== Examples
``` yaml
--- 
- name: Simple Recover
  evertrust.horizon.recover:

    endpoint: "https://url-of-the-api"
        
    x_api_id: "myId"
    x_api_key: "myKey"

    certificate_pem: <certificate_in_pem>

    password: "pAssw0rd"

- name: Simple Recover
  evertrust.horizon.recover:

    endpoint: "https://url-of-the-api"
        
    x_api_id: "myId"
    x_api_key: "myKey"

    certificate_pem: 
      src: pem/file/path

    password: "pAssw0rd"
```

== Status
=== Authors
- Evertrust R&D