= evertrust.horizon.horizon_inventory
Doc Writer Adrien Ducourthial <adu@evertrust.fr>
v2.0, {docdate}
:version: 2.0
:imagesdir: ./images
:title-page:
:numbered:
:toc:

== Synopsis
 - Get inventory hosts from Evertrust Horizon.
 - Use a YAML configuration file that ends with `horizon_inventory.(yml|yaml).`

== Requirements

== Parameters
=== Authent Parameters

To be authent on Horizon, you have to chose between log in with a certificate or with your login password. +
If you inform all the parameters, you will be log in priority by your certificate authent.

|===
| Parameter | Choices/Defaults | Configuration

| *client_cert* +
_path_
|
a| * The location of a client side certificate.
* authent value

| *client_key* +
_path_
|
a| * The location of a client side certificate's key.
* authent value

| *x_api_id* +
_string_
| 
a| * Horizon authentication id.
* authent value

| *x_api_key* +
_string_
|
a| * Horizon authentication key.
* authent value

| *ca_bundle* +
_path_
|
a| * The location of a CA Bundle to use when validating SSL certificates.
* optionnal
|===

=== Inventory Parameters

|===
| Parameter | Choices/Defaults | Configuration

| *endpoint* +
- / requiered +
_string_
| 
| url of the API

| *query* +
_string_
|
| 

| *fields* +
_list_
|
|

| *hostnames* +
_list_
| 
a| * A list in order of precedence for hostname variables.
* To use labels as hostnames use the syntax labels.<key>


|===

== Examples
``` yaml
---
# horizon_inventory.yaml

plugin: evertrust.horizon.horizon_inventory

# API path
endpoint: "https://url-of-the-api"

# login and password to connect to the API
x_api_id: "myId"
x_api_key: "myKey"

query: "null"
fields:

# hostname destination variable, order by preference
# values : [san.ip, san.dns, discoveryData.ip, discoveryData.Hostname, label.<key>]
hostnames:
  - san.dns
```

== Status
=== Authors
- Adrien Ducourthial