= evertrust.horizon.horizon_enroll
Doc Writer Adrien Ducourthial <adu@evertrust.fr>
v2.0, {docdate}
:version: 2.0
:imagesdir: ./images
:title-page:
:numbered:
:toc:

== Synopsis
Enroll a certificate on Horizon

== Requirements
The below requirements are needed on the host that executes this module.

* cryptography

== Parameters
|===
| Parameter | Choices/Defaults | Configuration

| *x_api_id* +
_string_
| 
a| * Horizon authentication id.
* authent value

| *x_api_key* +
_string_
|
a| * Horizon authentication key.
* authent value

| *ca_bundle* +
_path_
|
a| * The location of a CA Bundle to use when validating SSL certificates.
* authent value

| *client_cert* +
_path_
|
a| * The location of a client side certificate.
* authent value

| *client_key* +
_path_
|
a| * The location of a client side certificate's key.
* authent value

| *endpoint* +
_string_
| 
| Url of the API.

| *profile* +
_string_
| 
| Horizon profile to enroll certificate.

| *password* +
_string_
|
| Horizon password to enroll certificate.

| *key_type* +
_string_
|
| Key type 

| *mode* +
_string_
a| * centralized
* decentralized
| Certificate enrollement mode.

| *subject* +
_dict_
|
| Certificate subject.

| *sans* +
_dict_
| 
| Certificate subject alternates names.

| *labels* +
_dict_
| 
| Certificate labels.

|===

== Examples
``` yaml
---
- name: Simple centralize enroll
  evertrust.horizon.horizon_enroll:
      
    # login and password to connect to the API
    x_api_id: "myId"
    x_api_key: "myKey"

    endpoint: "https://url-of-the-api"
 
    mode: "centralized"

    password: "pAssw0rd"
    key_type: "rsa-2048"
 
    profile: "profile"
 
    subject:
      cn.1: "myCN"
 
    sans:
      dnsname.1: "myDnsname"
 
    labels:
      snow_id: "value1"
      exp_tech: "value2"

- name: decentralize enroll with csr
  evertrust.horizon.horizon_enroll:
      
    # login and password to connect to the API
    x_api_id: "myId"
    x_api_key: "myKey"

    endpoint: "https://url-of-the-api"
 
    mode: "decentralized"
    csr: <a_csr_file>

    password: "pAssw0rd"
    key_type: "rsa-2048"
 
    profile: "profile"
 
    subject:
      cn.1: "myCN"
 
    sans:
      dnsname: 
        - "myDnsName1"
        - "myDnsName2"
 
    labels:
      snow_id: "value1"
      exp_tech: "value2"

- name: decentralize enroll without csr
  evertrust.horizon.horizon_enroll:
      
    # login and password to connect to the API
    x_api_id: "myId"
    x_api_key: "myKey"

    endpoint: "https://url-of-the-api"
 
    mode: "decentralized"

    password: "pAssw0rd"
    key_type: "rsa-2048"
 
    profile: "profile"
 
    subject:
      cn.1: "myCN"
      ou:
        - "myFirstOU"
        - "mySecondOU"
 
    sans:
      dnsname.1: "myDnsname"
 
    labels:
      snow_id: "value1"
      exp_tech: "value2"
```

== Status
=== Authors
- Adrien Ducourthial