= evertrust.horizon.horizon_revoke
Doc Writer Adrien Ducourthial <adu@evertrust.fr>
v2.0, {docdate}
:version: 2.0
:imagesdir: ./images
:title-page:
:numbered:
:toc:

== Synopsis
Revoke a certificate on Horizon

== Requirements

== Parameters
=== Authent Parameters

To be authent on Horizon, you have to chose between log in with a certificate or with your login password. +
If you inform all the parameters, you will be log in priority by your certificate authent.

|===
| Parameter | Choices/Defaults | Configuration

| *client_cert* +
_path_
|
a| * The location of a client side certificate.
* authent value

| *client_key* +
_path_
|
a| * The location of a client side certificate's key.
* authent value

| *x_api_id* +
_string_
| 
a| * Horizon authentication id.
* authent value

| *x_api_key* +
_string_
|
a| * Horizon authentication key.
* authent value

| *ca_bundle* +
_path_
|
a| * The location of a CA Bundle to use when validating SSL certificates.
* optionnal
|===

=== Revoke Parameters

|===
| Parameter | Choices/Defaults | Configuration

| *endpoint* +
_string_
| 
| Url of the API.

| *certificate_pem* +
_string_
|
| A certificate pem, or the path to a certificate pem file.

| *revocation_reason* +
_string_
|
| The reason of the revoke

|===

== Examples
``` yaml
---
- name: Simple Revoke
  evertrust.horizon.horizon_revoke:

    endpoint: "https://url-of-the-api"
        
    x_api_id: "myId"
    x_api_key: "myKey"

    certificate_pem: <certificate_in_pem>

- name: Simple Revoke
  evertrust.horizon.horizon_revoke:

    endpoint: "https://url-of-the-api"
        
    x_api_id: "myId"
    x_api_key: "myKey"

    certificate_pem: 
      src: /pem/file/path
```

== Status
=== Authors
- Adrien Ducourthial