name: build_doc

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: pip install ansible antsibull-docs sphinx sphinx-ansible-theme

      - name: Init collection
        run: ansible-galaxy collection install .

      - name: Build ansible docs with antsibull-docs
        run: >
          antsibull-docs sphinx-init --use-current --squash-hierarchy
          --dest-dir=docs/ --project "Horizon Ansible"
          --title "Horizon Ansible Documentation" evertrust.horizon

      - name: Install requirements
        run: pip install -r ./docs/requirements.txt

      - name: Add custom script to reformat doc
        run: sed -i 's/\(sphinx-build.*\)/python reformat.py || python3 reformat.py\n\1/' docs/build.sh

      - name: Build with sphinx
        run: ./docs/build.sh

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build/html

  # Deployment job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
