name: Build documentation with antsibull
on: 
  workflow_dispatch:
  push:
#    tags:
#      - '*'

jobs:
  # Build job
  build: 
    name: 'Build ansible doc for horizon'
    runs-on: ubuntu-latest
    steps:
    - name: Check out Horizon-ansible
      uses: actions/checkout@v3
      with:
        path: horizon-ansible
    
    - name: install ansible
      run: sudo apt install ansible
    
    - run: ansible-galaxy collection init evertrust.horizon

    - name: install antsibull-docs
      run: python3 -m pip install antsibull-docs

    - name: build ansible doc with antsibull-doc
      run: antsibull-docs collection --use-current --squash-hierarchy --dest-dir=horizon-ansible/docs/ evertrust.horizon
    
    - name: add sphinx theme
      run: pip install sphinx-ansible-theme

    - name: build with sphinx
      run: cd horizon-ansible && sphinx-build docs/ docs/html
    
    - name: setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: ./docs/html

  # Deployment job
  deploy:
     # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
