name: Build documentation with antsibull
on: 
  workflow_dispatch:
  push:
    branches:
      - Adrien-updates
    tags:
      - '*'

jobs:
  build: 
    name: 'Build ansible doc for horizon'
    runs-on: ubuntu-latest

    steps:

    - name: Check out Horizon-ansible
      uses: actions/checkout@v3
      with:
        path: horizon-ansible
    
    - name: install antsibull
      run: python3 -m pip install antsibull

    - name: test linux commands
      run: |
        cd horizon-ansible
        ls -a
    
    - name: build ansible doc with antsibull-doc
      run: antsibull-docs collection --use-current --squash-hierarchy --dest-dir=horizon-ansible/docs/ evertrust.horizon
    
    - name: build with sphinx
      run: sphinx-build docs/ docs/html
      