---
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: runs-on=${{ github.run_id }}/runner=evertrust
    steps:
      - name: Configure Runs-On
        uses: runs-on/action@4e5f72399b6b17f2e79c511c1b38a315a64d22dc # v2.2.0

      - name: Setup ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
          submodules: true
          fetch-depth: 0

      - name: Configure mise-en-place
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Release check
        run: mise run release_check
        env:
          HORIZON_ENDPOINT: ${{ secrets.HORIZON_ENDPOINT }}
          HORIZON_API_ID: ${{ secrets.HORIZON_API_ID }}
          HORIZON_API_KEY: ${{ secrets.HORIZON_API_KEY }}

      - name: Publish collection
        run: mise run publish
        env:
          ANSIBLE_GALAXY_API_TOKEN: ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}
