name: Run test
on: 
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
    - name: 

    runs-on: ubuntu-latest
    steps:
    
    # - name: Setup creds
    #   run: |
    #     touch integration_config.yml
    #     echo x_api_id: ${{ secrets.HORIZON_API_ID }} > integration_config.yml
    #     echo x_api_key: ${{ secrets.HORIZON_API_KEY }} > integration_config.yml

    - name: Perform integration testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14
        target-python-version: 3.9
        testing-type: integration
        pre-test-cmd: |
          touch integration_config.yml
          echo x_api_id: ${{ secrets.HORIZON_API_ID }} > integration_config.yml
          echo x_api_key: ${{ secrets.HORIZON_API_KEY }} > integration_config.yml

    - name: Perform unit testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14
        target-python-version: 3.9
        testing-type: units
