name: Run test
on: 
  push:

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:

    - name: Perform integration testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14
        target-python-version: 3.9
        testing-type: integration
        pre-test-cmd: >-
          HORIZON_API_ID=${{ secrets.HORIZON_API_ID }}
          HORIZON_API_KEY=${{ secrets.HORIZON_API_KEY }}
          tests/integration/integration_config.yml.template > tests/integration/integration_config.yml

    - name: Perform unit testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14
        target-python-version: 3.9
        testing-type: units
