on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ansible

    - name: Set integration_config.yml
      run: >-
        echo "[endpoint: ${{ secrets.HORIZON_ENDPOINT }}, x_api_id: ${{ secrets.HORIZON_API_ID }}, x_api_key: ${{ secrets.HORIZON_API_KEY }}]" >> tests/integration/integration_config.yml

    - name: Run tests
      run: make test
