---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  integration:
    needs: unit
    permissions:
      contents: read
    runs-on: runs-on=${{ github.run_id }}/runner=evertrust
    timeout-minutes: 30
    steps:
    - name: Configure Runs-On
      uses: runs-on/action@4e5f72399b6b17f2e79c511c1b38a315a64d22dc # v2.2.0

    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        persist-credentials: false
        submodules: true

    - name: Configure mise-en-place
      uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

    - name: Fetch secrets via Vault
      uses: hashicorp/vault-action@9c2d817b85b9fff56bcab21cb74b485aee9e9d73 # v2.8.1
      with:
        url: ${{ vars.VAULT_ADDR }}
        method: ${{ vars.VAULT_AUTH_METHOD }}
        path: ${{ vars.VAULT_AUTH_PATH }}
        secrets: |
          /v1/ci/data/repositories/evertrust/horizon-ansible/horizon endpoint | HORIZON_ENDPOINT ;
          /v1/ci/data/repositories/evertrust/horizon-ansible/horizon api_id | HORIZON_API_ID ;
          /v1/ci/data/repositories/evertrust/horizon-ansible/horizon api_key | HORIZON_API_KEY ;

    - name: Run integration tests
      run: mise run integration_test
      env:
        HORIZON_ENDPOINT: ${{ env.HORIZON_ENDPOINT }}
        HORIZON_API_ID: ${{ env.HORIZON_API_ID }}
        HORIZON_API_KEY: ${{ env.HORIZON_API_KEY }}

  unit:
    runs-on: runs-on=${{ github.run_id }}/runner=evertrust
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Configure Runs-On
        uses: runs-on/action@4e5f72399b6b17f2e79c511c1b38a315a64d22dc # v2.2.0

      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Configure mise-en-place
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Run unit tests
        run: mise run unit_test
