on: 
  push:

jobs:
  test:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
    - name: Perform integration testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14
        target-python-version: 3.9
        testing-type: integration
        test-deps: community.crypto
        pre-test-cmd: >-
          echo "[endpoint: ${{ secrets.HORIZON_ENDPOINT }}, x_api_id: ${{ secrets.HORIZON_API_ID }}, x_api_key: ${{ secrets.HORIZON_API_KEY }}]" >> tests/integration/integration_config.yml

    - name: Perform unit testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.14
        target-python-version: 3.9
        testing-type: units
