---
name: Vulnerability scan

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
# syft & gryp
    steps:
      - name: Configure checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          path: .
          format: spdx-json
          upload-artifact: false
          output-file: horizon-ansible-sbom.spdx.json
          artifact-name: horizon-ansible-sbom.spdx.json

      - name: Scan SBOM with Grype
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          sbom: horizon-ansible-sbom.spdx.json
          severity-cutoff: high
          fail-build: false
          output-format: sarif
          output-file: grype-horizon-ansible.sarif

      - name: Upload Grype artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          path: |
            horizon-ansible-sbom.spdx.json
            grype-horizon-ansible.sarif
