---
name: Vulnerability scan

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  vulnerability_scan:
    runs-on: runs-on=${{ github.run_id }}/runner=evertrust
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Configure Runs-On
        uses: runs-on/action@4e5f72399b6b17f2e79c511c1b38a315a64d22dc # v2.2.0

      - name: Configure checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Configure mise-en-place
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Generate SBOM with Syft
        run: >-
          mise run sbom .
          -o horizon-ansible-sbom.spdx.json

      - name: Scan SBOM with Grype
        run: >-
          mise run scan:sbom horizon-ansible-sbom.spdx.json
          --fail-on high
          -o grype-horizon-ansible.sarif

      - name: Upload Grype artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          path: |
            horizon-ansible-sbom.spdx.json
            grype-horizon-ansible.sarif
